# This docker-compose file should only be used for development !

services:
  www_nibblepoker_lu:
    container_name: www-nibblepoker-python
    build:
      context: .
    ports:
      - 5001:5000
    environment:
      - TZ=Europe/Brussels
      - NP_HTML_POST_PROCESS=MINIFY
      - NP_FLASK_WAITRESS=1
      - NP_FLASK_PORT=80
    #volumes:
    #  - ./app/:/app:ro
    restart: unless-stopped
    stop_grace_period: 1s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
        driver: "json-file"
        options:
            max-size: "16m"
